/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(pss_tagger_cc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(bd836b89f8571aed0646a9cb6356680e)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/lte/pss_tagger_cc.h>
// pydoc.h is automatically generated in the build directory
#include <pss_tagger_cc_pydoc.h>

void bind_pss_tagger_cc(py::module& m)
{

    using pss_tagger_cc    = gr::lte::pss_tagger_cc;


    py::class_<pss_tagger_cc, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<pss_tagger_cc>>(m, "pss_tagger_cc", D(pss_tagger_cc))

        .def(py::init(&pss_tagger_cc::make),
           D(pss_tagger_cc,make)
        )
        



        ;




}








