/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(sss_tagger_cc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(84be79e62a7ef55a747a17b27f11d4a6)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/lte/sss_tagger_cc.h>
// pydoc.h is automatically generated in the build directory
#include <sss_tagger_cc_pydoc.h>

void bind_sss_tagger_cc(py::module& m)
{

    using sss_tagger_cc    = gr::lte::sss_tagger_cc;


    py::class_<sss_tagger_cc, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<sss_tagger_cc>>(m, "sss_tagger_cc", D(sss_tagger_cc))

        .def(py::init(&sss_tagger_cc::make),
           D(sss_tagger_cc,make)
        )
        



        ;




}








