/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(sync_frequency_c.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(9e9e96d395f533b3e2732971c5751592)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/lte/sync_frequency_c.h>
// pydoc.h is automatically generated in the build directory
#include <sync_frequency_c_pydoc.h>

void bind_sync_frequency_c(py::module& m)
{

    using sync_frequency_c    = ::gr::lte::sync_frequency_c;


    py::class_<sync_frequency_c, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<sync_frequency_c>>(m, "sync_frequency_c", D(sync_frequency_c))

        .def(py::init(&sync_frequency_c::make),
           py::arg("sig"),
           py::arg("fftl"),
           py::arg("name") = "sync_frequency_c",
           D(sync_frequency_c,make)
        )
        



        ;




}








