/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-lte
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_LTE_API_H
#define INCLUDED_LTE_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_lte_EXPORTS
#define LTE_API __GR_ATTR_EXPORT
#else
#define LTE_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_LTE_API_H */
